# Generated by Django 5.2.10 on 2026-01-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_platform_user_username_alter_apikeys_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
